skyway:
  # ここに構築済みのCloudflareのURLを指定します
  credentialServerUrl: 'https://your-backend-name.your-subdomain.workers.dev'
webrtc: #非推奨（旧SkyWay）
  key: aaaaaaaa-bbbb-ccccc-dddd-eeeeeeeeeeee #[deprecated] Your (old) SkyWay API key
app: #未使用
dice: #未使用